name: 'Keep-a-Changelog Get Release Notes'
description: 'Extracts the release notes for a version from a changelog'
inputs:
    release-version:
      description: >-
        The version for which to extract the release notes. Can be 'unreleased' to get the unreleased notes.
      required: false
      default: 'unreleased'
    changelog:
      description: >-
        The path to the changelog to examine. If a relative path is specified, it is appended to the GitHub workspace
        path.
      required: false
      default: 'CHANGELOG.md'
outputs:
  release-notes:
    description: 'The markdown content of the previously unreleased changelog section.'
runs:
    using: 'node16'
    main: ../dist/get-release-notes/index.js