# `dist/**/index.js` are special files in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate these files through a build process from other source files.
# We need to make sure the checked-in `index.js` files actually match what we expect them to be.
name: Ensure dist files are updated

on:
  pull_request:
    branches: 
    - main
    - release/*

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        persist-credentials: false

    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm ci

    - name: Rebuild the dist directory
      run: |
        npm run build
        npm run package

    # - name: Test echo
    #   run: |
    #     if [[ "${{ startsWith(github.event.pull_request.title, '[Snyk]') }}" == "true" ]]; then
    #       echo "Hmm"
    #     fi
    #     if [[ "${{ startsWith(github.event.pull_request.title, '[SnykXXX]') }}" != "true" ]]; then
    #       echo "Fee fi fo fum"
    #     fi
    #     echo "Committing rebuild code"
    #     echo "${{ github.ref }}"
    #     echo "${{ github.event.pull_request.head.ref }}"

    - name: Compare the expected and actual dist/ directories
      run: |
        if [ "$(git diff --ignore-space-at-eol --ignore-cr-at-eol -- dist/ ':(exclude)*.js.map' | wc -l)" -gt "0" ]; then
          if [[ "${{ startsWith(github.event.pull_request.title, '[Snyk]') }}" == "true" ]]; then
            echo "::set-output name=dist_update_required::true"
          else
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        fi
      id: diff

    # - uses: tibdex/github-app-token@v1
    #   if: startsWith(github.event.pull_request.title, '[Snyk]')
    #   id: generate-token
    #   with:
    #     app_id: ${{ secrets.TAGRELEASEBOT_APP_ID }}
    #     private_key: ${{ secrets.TAGRELEASEBOT_APP_KEY }}

    - name: Commit dist directory (Snyk)
      if: contains(steps.diff.outputs.dist_update_required, 'true')
      run: |
        echo "Committing rebuild code"
        echo "${{ github.ref }}"

    # If index.js was different than expected, upload the expected version as an artifact
    - uses: actions/upload-artifact@v2
      if: ${{ failure() && steps.diff.conclusion == 'failure' }}
      with:
        name: dist
        path: dist/