name: Test

on:
  workflow_dispatch:
    

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: release-flow/.github/actions/test@v1
        with:
          body: "body text"
          github_token: "1234"
          draft: true
          release_name: "Release xx"
          tag_name: "v-xx"
